FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Radiwa Server

## Users [/api/v1/users]

### List of Users [GET /api/v1/users]

+ Response 200 (application/json)

    + Body

            {
                "data": [
                    {
                        "id": "1",
                        "attributes": {
                            "username": "admin"
                        }
                    },
                    {
                       "id": "11",
                        "attributes": {
                            "username": "some-user-name"
                        }
                    }
                ]
            }

### User Info [GET /api/v1/users/{user_id}]

+ Response 200 (application/json)

    + Body

            {
                "data": {
                    "id": "11",
                    "attributes": {
                        "username": "some-user-name"
                    }
                }
            }

### Authorization [POST /api/v1/users/{user_id}]

+ Request (application/json)
        
    + Body

            {
                "data": {
                    "id": "11",
                    "attributes": {
                        "username": "some-user-name",
                        "password": "qwer123"
                    }
                }
            }

+ Response 200 (application/json)


    + Body

            {
                "data": {
                    "id": "11",
                    "attributes": {
                        "username": "some-user-name",
                        "access-token": "qweqwe"
                    }
                }
            }

### Create User [POST /api/v1/users]

+ Request (application/json)

    + Body

            {
                "data": {
                    "attributes": {
                        "username": "ivan",
                        "password": "strong password"
                    }
                }
            }
        
+ Response 201 (application/json)

    + Body

            {
                "data": {
                    "id": "12",
                    "attributes": {
                        "username": "ivan"
                    }
                }
            }

### Update User [PATCH /api/v1/users/{user_id}]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer ourAccessToken
            Location: /users/12

    + Body
    
            {
                "data": {
                    "id": "12",
                    "attributes": {
                        "username": "some-user",
                        "password": "new strong password"
                    }
                }
            }
        
+ Response 200 (application/json)

    + Body

            {
                "data": {
                    "id": "12",
                    "attributes": {
                        "username": "some-user"
                    }
                }
            }

### Destroy User [DELETE /api/v1/users/{user_id}]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer ourAccessToken

    + Body
    
            {
                "data": {
                    "id": "12"
                }
            }

+ Response 204 (application/json)